name: Build Release

on:
  release:
    types: [ created ]

jobs:
  build:
    name: Build Containers
    if: github.repository == 'xibosignage/xibo-cms'
    runs-on: ubuntu-18.04
    steps:
      - name: Build archive
        run: |
          docker pull xibosignage/xibo-cms:release-${GITHUB_REF##*/}
          CONTAINER=$(docker create xibosignage/xibo-cms:release-${GITHUB_REF##*/})
          docker cp "$CONTAINER":/var/www/cms/ xibo-cms-${GITHUB_REF##*/}
          tar -czf xibo-cms-${GITHUB_REF##*/}.tar.gz xibo-cms-${GITHUB_REF##*/}
          zip -rq xibo-cms-${GITHUB_REF##*/}.zip xibo-cms-${GITHUB_REF##*/}
          docker rm "$CONTAINER"
      - name: Upload CMS TAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./xibo-cms-${GITHUB_REF##*/}.tar.gz
          asset_name: xibo-cms-${GITHUB_REF##*/}.tar.gz
          asset_content_type: application/gzip
      - name: Upload CMS ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./xibo-cms-${GITHUB_REF##*/}.zip
          asset_name: xibo-cms-${GITHUB_REF##*/}.zip
          asset_content_type: application/zip

  # Skip in a fork
  in_fork:
    name: Skip in a fork
    runs-on: ubuntu-18.04
    if: github.repository != 'xibosignage/xibo-cms'
    steps:
      - name: Skip
        run: |
          echo 'Skipped while in a fork'